// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRouteAPI.Infrastructure.Persistence;


#nullable disable

namespace TravelRouteAPI.Migrations
{
    [DbContext(typeof(RouteDbContext))]
    [Migration("20250609024750_MAPICreate")]
    partial class MAPICreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TravelRouteAPI.Models.ChooseRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "BRC",
                            Origin = "GRU",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Destination = "SCL",
                            Origin = "BRC",
                            Price = 5m
                        },
                        new
                        {
                            Id = 3,
                            Destination = "CDG",
                            Origin = "GRU",
                            Price = 75m
                        },
                        new
                        {
                            Id = 4,
                            Destination = "SCL",
                            Origin = "GRU",
                            Price = 20m
                        },
                        new
                        {
                            Id = 5,
                            Destination = "ORL",
                            Origin = "GRU",
                            Price = 56m
                        },
                        new
                        {
                            Id = 6,
                            Destination = "CDG",
                            Origin = "ORL",
                            Price = 5m
                        },
                        new
                        {
                            Id = 7,
                            Destination = "ORL",
                            Origin = "SCL",
                            Price = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
